version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-1010}:1010"
    environment:
      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
      - PUBLIC_URL=${PUBLIC_URL}
      - PORT=${PORT:-1010}
    restart: unless-stopped
